### ISSUE TITLE
update link for Codemotion Madrid

### ISSUE THREAD

**Issue by francjp** [comunidad-tecnologica/awesome-spanish-slack-dev-groups#24]
Previous link to join Codemotion Madrid slack is no longer active, please update with this correct link: https://join.slack.com/t/codemotionspain/shared_invite/enQtNDI1ODAxMzc5MjA3LTAxZWU5Y2I3ZmMxNmIxMDdiMTJlOTVkODNiOWU2NDU1MDAxMzhlMjBiNzZjODEyYWY5MThjN2U0YjQ2ZGNiNTg

Thanks,
Francisco.-

**Comment by esebastian** [comment]
Done, thanks!
