### ISSUE TITLE
Not working links - communities

### ISSUE THREAD

**Issue by Eusebiotrigo** [comunidad-tecnologica/awesome-spanish-slack-dev-groups#29]
There are several communities in the Spain section no longer active:

https://asturiasdev.herokuapp.com/
http://barcelonajs.herokuapp.com/
http://slack.ciudadrealrb.org/
https://cyliconvalley.herokuapp.com/
https://kiwi-slack.herokuapp.com/
http://laraveles-slack.bigcode.eu/
http://madriddevs.org/
http://magesp.codezz.co/
http://nodeschoolmadrid.herokuapp.com/
https://invitations-osweekends.herokuapp.com/
http://progfunc.es/
http://slack.scalabcn.org/
https://wpmadrid.es/wp-login.php?action=slack-invitation should be https://wpmadrid.slack.com/

The invite links for the following don't work anymore:
https://comunidadestecnicas.slack.com/
https://anuncioswp.slack.com
https://corunadevelopers.slack.com/
https://huelva-developers.slack.com/
https://phpsevilla.slack.com/
https://salamancadevs.slack.com/
https://programaresunamierda.slack.com/

This workspace has been deleted:
https://uhjrxlevy-malagascala.slack.com/

**Comment by jarcos** [comment]
TBH, we (huelva-developers community) removed the invite link because we received a few spammers after adding the link here. Do you think folks that there is a way to let people know that the team is open but for real people?
